### ISSUE TITLE
Incompatible with Composer v2 / still needed?

### ISSUE THREAD

**Issue by soWizardly** [wikimedia/composer-merge-plugin#191] opened 2020-10-26 21:35 UTC
Composer v2 was released this weekend, and is not compatible with the current version of this plugin. I am openly wondering whether this package would still be needed in v2 and/or if an update is being planned. I plan on doing some googling myself to confirm, but wanted to post this in the mean time.

**Comment by bd808** [comment] 2020-10-26 21:48
Duplicate of #184

**Closed by bd808** 2020-10-26 21:48 UTC
