### ISSUE TITLE
aliases on requires from included configs don't seem to work

### ISSUE THREAD

**Issue by far-blue** [wikimedia/composer-merge-plugin#100] opened 2016-01-05 12:05 UTC
I have a composer.json with a requirement on package A and a requirement on package B:

```
{
  "require": {
    "A": "dev-trunk",
    "B": "dev-trunk"
  }
}
```

package B also has a requirement on package `A @ dev-trunk`.

If I try to change the version of package A in my secondary config file with something like:

```
{
  "require": {
    "A": "dev-feature as dev-trunk"
  }
}
```

I would expect this to work fine because the alias statement should then mean package B's need for `A @ dev-trunk` will still be met (via the alias).

However, I get a conflict resolution failure.

The output differs depending on whether I have "replace" mode true or false but the end result is the same failure to resolve.

**Comment by helmuthva** [comment] 2017-09-05 10:43
any progress on this issue? can be reproduced easily.

**Comment by hexus** [comment] 2018-07-02 10:03
Aliases are explicitly dropped here.

https://github.com/wikimedia/composer-merge-plugin/blob/7eca510/src/Merge/StabilityFlags.php#L151-L152

**Comment by XedinUnknown** [comment] 2021-06-14 16:55
Any movement here, colleagues?

**Comment by hexus** [comment] 2021-06-14 20:57
There hasn't been in years but I'm thinking of picking this up myself

**Comment by XedinUnknown** [comment] 2021-06-15 07:13
I'm not very familiar with the internals of this plugin, but if someone who is would like to pick this up, I can review.

**Comment by sajphon** [comment] 2021-06-15 09:51
> I'm not very familiar with the internals of this plugin, but I think the solution has already been implemented in #196, and it's just down to being reviewed and merged, as it has apparently been ready for a few months now, @hexus.

Yup, it only needs to be merged i think. I am using the latest commit from #196 PR and it works flawlessly.

**Comment by hexus** [comment] 2021-06-15 11:43
Oh, awesome. Indeed, just a case of waiting for #196 to be merged and released then!

**Comment by XedinUnknown** [comment] 2021-06-15 17:12
I doubt that it's just that, because we've been doing just that since January :D

I'm not suggesting to pester the maintainers, but to make their job easier by attracting attention to the PR, reporting test results, etc.

**Closed** 2022-08-22 13:27 UTC
Labels: bug
