### ISSUE TITLE
Merged VCS repositories aren't installed

### ISSUE THREAD

**Issue by robbytaylor** [wikimedia/composer-merge-plugin#71] opened 2015-09-11 14:50 UTC
I've got a project with a main composer.json and a merged composer.json which I'm trying to use to install a private git project.

With the repository and require config in the merged JSON file the project isn't installed with composer giving a 'package ... could not be found in any version' error.

Moving the repository and require to the main composer.json files results in the package being installed.

A package which is listed on packagist (doesn't require a repository entry in the composer config) installs ok from the merged file.

The installed composer-merge-plugin is at 361e098955069062c2d688a2c116d7dd837acb38

**Comment by bd808** [comment] 2015-09-11 15:52
@robbytaylor Thanks for the bug report. Can you try to come up with a minimal replication of this issue that we can use for verification and testing of possible fixes? An good example of a helpful reproduction case would be the initial report of issue #62

**Comment by robbytaylor** [comment] 2015-09-14 15:09
Ok, so I've figured out the problem only exists when using a branch other than master.

I've created a repository at https://github.com/robbytaylor/test with a composer.json file which gives the package name as robbytaylor/test. This repository has two branches `master` and `1.0`.

To reproduce:

* Create an empty directory
* Create a composer.json file containing:

```
{
        "require": {
                "wikimedia/composer-merge-plugin": "^1.3@dev"
        },
        "prefer-stable": true,
        "config": {
                "preferred-install": "dist"
        },
        "minimum-stability": "dev",
        "extra": {
                "merge-plugin": {
                        "include": [
                                "composer.local.json"
                        ]
                }
        } 
}
```

* Create a composer.local.json file:

```
{
        "require": {
                "robbytaylor/test": "1.*"
        },
        "repositories": [
                {
                        "type": "vcs",
                        "url": "git@github.com:robbytaylor/test"
                }
        ]
}
```

* Run `composer update`

After running `composer update` you'll get the "Your requirements could not be resolved to an installable set of packages" composer error.

* Replace the contents of composer.json with:

```
{
	"require": {
		"wikimedia/composer-merge-plugin": "^1.3@dev",
		"robbytaylor/test": "1.*"
	},
        "prefer-stable": true,
        "config": {
                "preferred-install": "dist"
        },
	"minimum-stability": "dev",
	"extra": {
		"merge-plugin": {
			"include": [
				"composer.local.json"
			]
		}
	},
	"repositories": [
		{
			"type": "vcs",
			"url": "git@github.com:robbytaylor/test"
		}
	]
}
```

* And changed composer.local.json to:

```
{}
```

* The package will now install correctly:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)         
  - Installing robbytaylor/test (1.0.x-dev 3362a1c)
    Loading from cache

Writing lock file
Generating autoload files
```

The package is also installed if the required version given in composer.local.json is 'dev-master' instead of '1.*'.

Hope that helps, please let me know if I've missed anything.

**Comment by bd808** [comment] 2015-10-01 16:37
I think this may be fixed by #67. I need to rebase that patch and then we can test it out. We have a whole class of problems with aliased root packages and I think this is a variation on that.

**Comment by bd808** [comment] 2015-10-27 05:33
Retested after https://github.com/wikimedia/composer-merge-plugin/commit/f706e5ce863ee7f3cf61f165e120d547c64b1a78 was merged.

I can still reproduce the 'package ... could not be found in any version' result. If I change composer.local.json from ` "robbytaylor/test": "1.*"` to ` "robbytaylor/test": "1.*@dev"` then both `composer install` on a clean directory and `composer update` on a previously failed install work.

This seems to have something to do with how stability flags are handled through our plugin.

**Comment by bd808** [comment] 2015-10-27 05:48
This is defiantly caused by ExtraPackage::mergeStabilityFlags. By adding some local logging I can see that it is marking the `robbytaylor/test` package as needing to be a stable version when the "@dev" modifier is not used. This functionality was introduced in 0a54f7fa8e8f61eed5d678dfa9d8c66c88640ba1 to address #9 (Minimum stability not updated by merged settings). It looks like my solution there is too naive.

**Closed** 2015-10-28 16:27 UTC
Labels: bug

**Comment by robbytaylor** [comment] 2015-10-28 16:28
Nice! Thanks :)

**Comment by ghprod** [comment] 2015-11-06 14:35
Hi i still have this problem, do i need to use dev-master to solve this issue?

**Comment by ghprod** [comment] 2015-11-06 15:18
Try it with `dev-master` and still no luck, also add `"minimum-stability": "dev",` give me same result ..

Any idea? These are my dummy composer

### Main composer.json

```
{
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "wikimedia/composer-merge-plugin": "dev-master",
        "caffeinated/modules": "dev-master#42fbc67"
    },
    "config": {
        "preferred-install": "dist"
    },
    "extra": {
        "merge-plugin": {
            "include": [
                "public/modules/*/composer.json"
            ]
        }
    }
}

### Another composer.json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/ghprod/laravel-menu"
        }
    ],
    "require": {
        "lavary/laravel-menu": "dev-master#956e50f",
    }
}

And that `lavary/laravel-menu` still downloading original source, not my vcs :(

Thanks

**Comment by ghprod** [comment] 2015-11-06 16:00
From Log i can see that vcs is processed

```
  [merge-plugin] Loading public/modules/Dashboard/composer.json...
  [merge-plugin] Adding vcs repository
  [merge-plugin] Adding vcs repository
  [merge-plugin] Merging lavary/laravel-menu

...

Downloading https://api.github.com/repos/ghprod/laravel-menu
Downloading https://api.github.com/repos/ghprod/laravel-menu/contents/composer.json?ref=master
Downloading https://api.github.com/repos/ghprod/laravel-menu/commits/master
Downloading https://api.github.com/repos/ghprod/laravel-menu/tags?per_page=100
Downloading https://api.github.com/repos/ghprod/laravel-menu/git/refs/heads?per_page=100
Reading composer.json of lavary/laravel-menu (v1.5.1)
Reading /home/ferri/.composer/cache/repo/github.com/ghprod/laravel-menu/ded66869296a08364f5c4ffb59a394632b047b35 from cache


....

## But in the end its still using original repo

  - Installing lavary/laravel-menu (dev-master bebce99)
Reading /home/ferri/.composer/cache/files/lavary/laravel-menu/bebce996ef08cf911da0139c30a2da03a2768326.zip from cache
    Loading from cache
    Extracting archive
```

Thanks, need your helps :)
